apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  group: {{ .Values.app.group }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        group: {{ .Values.app.group }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.container.image.repository }}:{{ .Values.app.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.container.image.pullPolicy }}
          ports:
              - containerPort: {{ .Values.app.container.port }}
                name: {{ .Values.app.name }}
          livenessProbe:
            httpGet:
              path: /health_check
              port: {{ .Values.app.container.port }}
          readinessProbe:
            httpGet:
              path: /health_check
              port: {{ .Values.app.container.port }}
