# Contains default app-level properties
# to be overridden in files under 'values' folder
app:
  name: app
  group: backend
  replicaCount: 1
  container:
    image:
      repository: "375158168967.dkr.ecr.us-east-2.amazonaws.com"
      pullPolicy: IfNotPresent
# for local env
#      repository: "me.local"
#      pullPolicy: Never

    port: 8080
    healthCheckPath: /health_check
    plainEnv:
      DUMMY: dummy
      DB_HOST: terraform-20230526101117284400000014.cisxpoiobdgl.***.rds.amazonaws.com
    secretEnv:
      DB_PASS: db-pass

  service:
    type: ClusterIP
    port: 8080
