# Contains default app-level properties
# to be overridden in files under 'values' folder
app:
  name: app
  group: backend
  replicaCount: 1
  container:
    image:
#      repository: "375158168967.dkr.ecr.us-east-2.amazonaws.com"
      repository: "me.local"
      pullPolicy: IfNotPresent

    port: 8080
    healthCheckPath: /health_check
    env:
      DUMMY: dummy
  service:
    type: ClusterIP
    port: 8080
