# Contains default app-level properties
# to be overridden in files under 'values' folder
app:
  name: app
  group: backend
  replicaCount: 1
  container:
    image:
      repository: "${AWS_DOMAIN_OWNER_ID}.dkr.ecr.us-east-2.amazonaws.com"
      pullPolicy: Always

    port: 8080
    config: []
    env:
      - key: key
        value: value
  service:
    type: ClusterIP
    port: 80
