ingress:
  name: ingress-service
  replicaCount: 1
  annotations:
    class: nginx
  hosts:
    - host: host
      paths:
        - path: /
          backend:
            serviceName: name
            servicePort: 80

    - host: host
      paths:
        - path: /
          backend:
            serviceName: name
            servicePort: 80
