ingress:
  name: ingress-service
  replicaCount: 1
  annotations:
    class: nginx
  hosts:
    - host: dummy
      paths:
        - path: dummy
          backend:
            serviceName: dummy
            servicePort: dummy
