apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  namespace: db
  labels:
    app.kubernetes.io/name: postgres # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  sessionAffinity: None
  ports:
    - port: 5432 # Sets port to run the postgres application
  selector:
    app.kubernetes.io/name: postgres
