apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      initContainers:
        - name: init-redis
          image: "{{.Values.image.repository}}/{{.Values.image.tag}}"
          command:
            - bash
            - "-c"
            - |
              set -ex
              # Generate redis server-id from pod ordinal index.
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              # Copy appropriate redis config files from config-map to respective directories.
              if [[ $ordinal -eq 0 ]]; then
                cp /mnt/master.conf /etc/redis-config.conf
              else
                cp /mnt/slave.conf /etc/redis-config.conf
              fi
          volumeMounts:
            - name: redis-claim
              mountPath: /etc
            - name: config-map
              mountPath: /mnt/
      containers:
        - name: redis
          image: "{{.Values.image.repository}}/{{.Values.image.tag}}"
          ports:
            - name: redis
              containerPort: 6379
          command:
            - redis-server
            - "/etc/redis-config.conf"
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-claim
              mountPath: /etc
      volumes:
        - name: config-map
          configMap:
            name: redis-configuration
  volumeClaimTemplates:
    - metadata:
        name: redis-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
