apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  defaultBackend:
    service:
      name: "yellow-taxi-api"
      port:
        number: 80
  ingressClassName: {{ .Values.ingress.annotations.class }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .backend.serviceName }}
            port:
              number: {{ .backend.servicePort }}
      {{- end }}
  {{- end }}
