apiVersion: batch/v1
kind: CronJob
metadata:
  name: totals
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: totals
              image: "{{ .Values.job.container.image.repository }}/{{ .Values.job.container.image.name }}:{{ .Values.job.container.image.versionTag }}"
              imagePullPolicy: "{{.Values.image.pullPolicy}}"

          restartPolicy: OnFailure
