apiVersion: batch/v1
kind: CronJob
metadata:
  name: totals
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "{{ .Values.job.name }}-test-service-account"
          containers:
            - name: totals
              image: "{{ .Values.job.container.image.repository }}/{{ .Values.job.container.image.name }}:{{ .Values.job.container.image.versionTag }}"
              imagePullPolicy: "{{.Values.job.container.image.pullPolicy}}"
              env:
                {{- range $key, $value := .Values.job.container.plainEnv }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- range $key, $value := .Values.job.container.secretEnv }}
                - name: {{ $key }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $value | quote }}
                      key: "{{ $value }}"
                {{- end }}
              volumeMounts:
                - name: secrets-store-inline
                  mountPath: "/mnt/secrets-store"
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: secrets-store-inline
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "yt-secrets"
