apiVersion: batch/v1
kind: CronJob
metadata:
  name: totals
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: totals
              image: "{{ .Values.job.container.image.repository }}/{{ .Values.job.container.image.name }}:{{ .Values.job.container.image.versionTag }}"
              imagePullPolicy: "{{.Values.job.container.image.pullPolicy}}"
              env:
                {{- range $key, $value := .Values.job.container.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
          restartPolicy: OnFailure
