apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.job.name }}-service-account"
  namespace: yellow-taxi
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::375158168967:role/eks-service-account-role
