apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-letsencrypt
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: paulsegfault@gmail.com
    privateKeySecretRef:
      name: issuer-letsencrypt
    solvers:
      - dns01:
          route53:
            region: us-east-2
            hostedZoneID: Z06416532XSNCG31SKCMA
{{/*      - http01:*/}}
{{/*          ingress:*/}}
{{/*            class: external-nginx*/}}
