apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: paulsegfault@gmail.com
    privateKeySecretRef:
      name: cluster-issuer-letsencrypt
    solvers:
      - http01:
          ingress:
            class: alb
