apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: paulsegfault@gmail.com
    privateKeySecretRef:
      name: issuer-letsencrypt
    solvers:
      - dns01:
          route53:
            region: us-east-2
            hostedZoneID: Z1042193JPK8JIW9RFJ
{{/*      - http01:*/}}
{{/*          ingress:*/}}
{{/*            class: external-nginx*/}}
