apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: yellow-taxi
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        group: {{ .Values.app.group }}
    spec:
      serviceAccountName: "{{ .Values.app.name }}-service-account"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "yt-secrets"
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.container.image.repository }}/{{ .Values.app.container.image.name }}:{{ .Values.app.container.image.versionTag }}"
          imagePullPolicy: {{ .Values.app.container.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.container.port }}
              name: {{ .Values.app.name }}
          env:
            {{- range $key, $value := .Values.app.container.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: {{ .Values.app.container.healthCheckPath | quote }}
              port: {{ .Values.app.container.port }}
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: {{ .Values.app.container.healthCheckPath | quote }}
              port: {{ .Values.app.container.port }}

