{{- range .Values.secret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: yellow-taxi

spec:
  refreshInterval: 1m
  secretStoreRef:
    name: yt-secret-store
    kind: SecretStore
  target:
    name: {{ .secretTargetKey }}
{{/*    creationPolicy: Owner*/}}
  data:
    - secretKey: "{{ .secretTargetKey }}-secret-key"
      remoteRef:
        key: "{{ .secretSourceKey }}"
{{- end }}