{{- range $name := $.Values.namespaces }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: yt-secret-store
  namespace: {{ $name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: secret-store-service-account
---
{{- range $.Values.secrets}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .secretName }}
  namespace: {{ $name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: yt-secret-store
    kind: SecretStore
  target:
    name: {{ .secretTargetKey }}
{{/*    creationPolicy: Owner*/}}
  data:
    - secretKey: "{{ .secretTargetKey }}-secret-key"
      remoteRef:
        key: "{{ .secretSourceKey }}"
{{- end}}
{{- end}}