{{/*apiVersion: external-secrets.io/v1beta1*/}}
{{/*kind: SecretStore*/}}
{{/*metadata:*/}}
{{/*  name: yt-secret-store*/}}
{{/*  namespace: yellow-taxi*/}}
{{/*spec:*/}}
{{/*  provider:*/}}
{{/*    aws:*/}}
{{/*      service: SecretsManager*/}}
{{/*      region: us-east-2*/}}
{{/*      auth:*/}}
{{/*        jwt:*/}}
{{/*          serviceAccountRef:*/}}
{{/*            name: secret-store-service-account*/}}
