{{/*apiVersion: secrets-store.csi.x-k8s.io/v1*/}}
{{/*kind: SecretProviderClass*/}}
{{/*metadata:*/}}
{{/*  name: yt-secrets*/}}
{{/*  namespace: yellow-taxi*/}}
{{/*spec:*/}}
{{/*  provider: aws*/}}
{{/*  parameters:*/}}
{{/*    objects: |*/}}
{{/*      - objectName: "arn:aws:secretsmanager:us-east-2:375158168967:secret:prod_yt_db_pass-l1qNmO"*/}}
{{/*        objectAlias: DB_PASSWORD*/}}

{{/*  secretObjects:*/}}
{{/*    - secretName: database_password*/}}
{{/*      type: Opaque*/}}
{{/*      data:*/}}
{{/*        - objectName: "DB_PASSWORD"*/}}
{{/*          key: password*/}}
