apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: yt-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod_yt_db_pass"
        objectAlias: DB_PASSWORD

  secretObjects:
    - secretName: database_password
      type: Opaque
      data:
        - objectName: "DB_PASSWORD"
          key: password
