apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: yt-secrets
  namespace: yellow-taxi
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prot_yt_db"
        objectType: "secretsmanager"
#  secretObjects:
#    - secretName: prot_yt_db
#      type: Opaque
#      data:
#        - key: username
#          objectName: myusername
#        - key: password
#          objectName: mypassword
