apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: yt-secrets
  namespace: yellow-taxi
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod_yt_db_pass"
        objectType: "secretsmanager"
        objectAlias: DB_PASSWORD

  secretObjects:
    - secretName: database_password
      type: Opaque
      data:
        - key: db_pass
          objectName: DB_PASSWORD
          objectPath: 'SecretString'
          objectType: raw
