apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: yt-secrets
spec:
  provider: aws
 # parameters:
 #   objects:
 #     - objectName: "arn:aws:secretsmanager:us-east-2:375158168967:secret:prot_yt_db"
      #- objectName: "arn:aws:secretsmanager:us-east-2:375158168967:secret:prot_yt_kafka" #Todo
  secretObjects:
    - secretName: prot_yt_db
      type: Opaque
      data:
        - key: username
          objectName: myusername
          version: AWSCURRENT
        - key: password
          objectName: mypassword
          version: AWSCURRENT