apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: yt-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod_yt_db_pass"
        objectType: "secretsmanager"
        objectAlias: db-pass1

  secretObjects:
    - secretName: db-pass1
      type: Opaque
      data:
        - objectName: "db-pass1"
          key: db-pass1
