ingress:
  name: ingress-service
  replicaCount: 1
  annotations:
    class: nginx
  hosts:
    - host: yellowtaxi.com
      paths:
        - path: /
          backend:
            serviceName: yellow-taxi-api
            servicePort: 80
