cert-manager:
  installCRDs: true
  # DNS-01 Route53
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::375158168967:role/eks-cert-manager-acme
  extraArgs:
    - --issuer-ambient-credentials
    - --dns01-recursive-nameservers-only
    - --dns01-recursive-nameservers=10.0.38.214:53,10.0.46.148:53
