cert-manager:
  installCRDs: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
  # DNS-01 Route53
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::375158168967:role/eks-cert-manager-acme
  extraArgs:
    - --issuer-ambient-credentials
