name: Microservice Manifests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: echo hello
